### PR TITLE
Return None for invalid day.

### PR DESCRIPTION
**Pull request by viniciuschiele**
This pull request validates the day considering also the leap years.

### CODE REVIEW

**Comment by lucasvo** [comment]
fixes #22

**Comment by thomasst** [comment]
Thanks! How about we only calculate `leap` if the month is 2 and the day is > 28?

**Comment by viniciuschiele** [comment]
That's a good idea, thanks.

**Comment by lucasvo** [comment]
@viniciuschiele tests.py still has a conflict with the previous PR that was merged. Any chance you could fix them? I'll nudge Thomas to merge it and ship a new version after that.

**Comment by viniciuschiele** [comment]
Sorry for the delay, I was on vacation.

I've fixed the conflicts.

Thanks

**Comment by thomasst** [comment]
Thanks! Merging this in #23

**Pull request closed without merging**
