### PR TITLE
Fixed two memory leaks where timedelta objects were not being cleaned

### PR DESCRIPTION
**Pull request by movermeyer**
- Fixed a memory leak in Python 3.7 parsing of timestamps with timezone information.
- Fixed a memory leak in the special midnight case.

### CODE REVIEW

**Comment by thomasst** [comment]
I'll merge this, #50, and #46 for a 2.0.1 release later this weekend.

**Comment by movermeyer** [comment]
My good friend @NickG123 felt like something was wrong while looking at my #48 changes.

We looked more closely and found these.

**Comment by movermeyer** [comment]
BTW, do you know of any tooling we could use to catch these sorts of errors earlier? I've been trying to use Valgrind, but haven't been able to get it to notice these.

Ideally, we would be able to add something to CircleCI to help detect these.

**Comment by thomasst** [comment]
I don't know – I was also going to suggest Valgrind.

**Pull request merged**
